export { default as Tabs } from "./Tabs"
export { default as Tab } from "./Tab"
export { default as TabsNav } from "./TabsNav"
export { default as TabFigure } from "./TabFigure"
export { default as TabLabel } from "./TabLabel"
