export { default as TabsSkeleton } from "./Tabs.Skeleton"
export { default as BaseTabs } from "./BaseTabs"
export { default as Tabs } from "./Tabs"
export { default as TabSkeleton } from "./Tab.Skeleton"
export { default as BaseTab } from "./BaseTab"
export { default as Tab } from "./Tab"
export { default as NumberedTabs } from "./NumberedTabs"
export { default as NumberedTab } from "./NumberedTab"
export { TabsNav } from "./TabsNav"
export { NumberedTabFigure } from "./NumberedTabFigure"
export { NumberedTabLabel } from "./NumberedTabLabel"
